language: node_js
node_js:
  - 8

install: 
  - npm ci

script: 
  # - npm run lint
  # - npm run test
  - npm run build

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: GH_API_KEY  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

notifications: 
  email:
    on_success: never
    on_failure: always